
```{r, include=FALSE}
library(feather)
library(tidyr)
library(dplyr)
```

```{r}
creditos <- read_feather("../pipeline/preprocess/output/design_matrix_20180823_prod.feather")

limpieza <- read_feather("../pipeline/preprocess/output/limpieza_20180823_prod.feather")

collapse <- read_feather("../pipeline/wrangle_train/output/collapse_train_20180823_prod.feather")
```

```{r}
head(limpieza)
```

```{r}
dim(limpieza)
```

```{r}
summary(as.factor(limpieza$min_fecha))
```

```{r}
summary(as.factor(limpieza$max_fechaCorteDespues))
```

```{r}
sum(limpieza$min_fecha_na)
```

```{r}
colocadoras <- limpieza$pkcolocadora[limpieza$min_fecha_na == 1]
length(colocadoras)
# Muy sospechoso!!!
# creditos[creditos$pkcolocadora %in% colocadoras, ] %>% View()
```

```{r}
sum(limpieza$indice_primer_saldo == 1, na.rm = TRUE)
hist(limpieza$indice_primer_saldo[limpieza$indice_primer_saldo > 1])
```

```{r}
hist(limpieza$indice_ultimo_saldo)
```

```{r}
sum(limpieza$indice_primer_saldo == 0, na.rm = TRUE)
sum(limpieza$indice_ultimo_saldo == 0, na.rm = TRUE)
sum(limpieza$indice_ultimo_saldo < limpieza$indice_primer_saldo, na.rm = TRUE)
```

```{r}
colocadoras <- limpieza$pkcolocadora[limpieza$indice_primer_saldo == 0 & !is.na(limpieza$indice_primer_saldo)]
length(colocadoras)
#creditos[creditos$pkcolocadora %in% colocadoras, ]
```

```{r}
xx <- limpieza$num_indices_total - limpieza$indice_ultimo_saldo
hist(xx[xx > 0])
```

```{r}
sum(is.na(limpieza$fechas_faltantes))
sum(limpieza$fechas_faltantes, na.rm = TRUE)
```

```{r}
sum(is.na(limpieza$fechas_repetidas))
sum(limpieza$fechas_repetidas > 0, na.rm = TRUE)
```

```{r}
sum(is.na(limpieza$max_fechas_faltantes_seguidas))
hist(limpieza$max_fechas_faltantes_seguidas)
```

```{r}
sum(is.na(limpieza$fin_antes_2013))
sum(limpieza$fin_antes_2013, na.rm = TRUE)
```

```{r}
sum(is.na(limpieza$historia_saldo_corta))
sum(limpieza$historia_saldo_corta, na.rm = TRUE)
```
